/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filetransferproject;

import java.io.File;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author HP PAVİLİON 15
 */
public class ClientForm extends javax.swing.JFrame {

    /**
     * Creates new form ClientForm
     */
    public static final int PORT = 3332;
    final JFileChooser fileChooser = new JFileChooser();
    public ClientForm() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendFile = new javax.swing.JButton();
        choseFile = new javax.swing.JButton();
        fileName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ip = new javax.swing.JTextField();
        txt_port = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lists = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filenamee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sendFile.setText("Gönder");
        sendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFileActionPerformed(evt);
            }
        });
        getContentPane().add(sendFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 119, -1));

        choseFile.setText("Dosya Seç");
        choseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choseFileActionPerformed(evt);
            }
        });
        getContentPane().add(choseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 119, -1));
        getContentPane().add(fileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 142, 44, -1));

        jLabel1.setText("IP Adresi:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, -1, -1));

        jLabel2.setText("Port:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 117, -1, -1));

        txt_ip.setText("127.0.0.1");
        getContentPane().add(txt_ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 145, 25));

        txt_port.setText("3332");
        getContentPane().add(txt_port, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 104, 145, 25));

        jButton1.setText("Listele");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 119, -1));

        jButton2.setText("İndir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 120, -1));

        lists.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Dosyalarım" }));
        getContentPane().add(lists, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 145, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 237, 160, 20));
        getContentPane().add(filenamee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 142, 337, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choseFileActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            filenamee.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_choseFileActionPerformed

    private void sendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFileActionPerformed
        // TODO add your handling code here:
        try {
            Client c=new Client();
            Socket s=new Socket(txt_ip.getText(),Integer.parseInt(txt_port.getText()));
            jLabel5.setText(c.sendFile(s,filenamee.getText()));
            
        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_sendFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Socket s;

        try {
            s = new Socket(txt_ip.getText(), Integer.parseInt(txt_port.getText()));
            Client tc = new Client();
            File root = new File("C:\\Users\\HP PAVİLİON 15\\Documents\\NetBeansProjects\\FileTransferProject\\File");
            File[] list = root.listFiles();
            

            for (File f : list) {
                if (f.isDirectory()) {
                } else {
                    System.out.println("Dosya:" + f.getName());
                    lists.addItem(f.getName()+"");
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Client c=new Client();
        Socket s;
        Server ser=new Server();
        try {
            s = new Socket(txt_ip.getText(),Integer.parseInt(txt_port.getText()));
            ser.sendFile(s, lists.getSelectedItem().toString());
        } catch (IOException ex) {
            Logger.getLogger(ClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choseFile;
    private javax.swing.JLabel fileName;
    private javax.swing.JLabel filenamee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> lists;
    private javax.swing.JButton sendFile;
    private javax.swing.JTextField txt_ip;
    private javax.swing.JTextField txt_port;
    // End of variables declaration//GEN-END:variables
}
